/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f103xxx.h"
#include "gpio_f103.h"
#include "systick_f103.h"

void DV_GPIO_Inits(void);
int main(void)
{
	DV_GPIO_Inits();
	Init_systick_time();
    /* Loop forever */
	while (1){
		GPIO_WritePin(GPIOA,GPIO_PIN_1,GPIO_PIN_SET);
		delay_ms(1000);
	}
	return 0;
}
void DV_GPIO_Inits(void){
	GPIO_Handle_t GPIO_Handle;
	GPIO_Handle.GPIOx = GPIOA;
	GPIO_Handle.GPIOConfig.GPIO_Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_Handle.GPIOConfig.GPIO_Pin_Number = GPIO_PIN_1;
	GPIO_Handle.GPIOConfig.GPIO_Speed = GPIO_OUT_SPEED_10MHZ;
	GPIO_Handle.GPIOConfig.GPIO_type = GPIO_NOPULL;
	GPIO_Init(&GPIO_Handle);
}
