/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "gpio_f407.h"
int main(void)
{
	GPIO_Handle_t GPIOLed1, Button;
	GPIO_SETUP1(GPIOLed1);
	GPIO_SETUP2(Button);
	GPIO_Init(&GPIOLed1);
	GPIO_Init(&Button);
    /* Loop forever */
	while(1){
		GPIO_WriteToPin(GPIOA, GPIO_PIN_3, GPIO_PIN_SET);
		GPIO_WriteToPin(GPIOA, GPIO_PIN_3, GPIO_PIN_RESET);
	}
}
void GPIO_SETUP1(GPIO_Handle_t GPIOHandle){
	GPIOHandle.GPIOx = GPIOA;
	GPIOHandle.Pinconfig.GPIO_Pinmode = GPIO_MODE_OUT;
	GPIOHandle.Pinconfig.GPIO_Pinnumber = GPIO_PIN_3;
	GPIOHandle.Pinconfig.GPIO_PinOPtyple =GPIO_TYPE_PP;
	GPIOHandle.Pinconfig.GPIO_PinPuPdControl = NO_GPIO_PU_PD;
	GPIOHandle.Pinconfig.GPIO_Pinspeed = GPIO_SPEED_MEDIUM;
}
void GPIO_SETUP2(GPIO_Handle_t GPIOHandle){
	GPIOHandle.GPIOx = GPIOA;
	GPIOHandle.Pinconfig.GPIO_Pinmode = GPIO_MODE_IN;
	GPIOHandle.Pinconfig.GPIO_Pinnumber = GPIO_PIN_11;
	GPIOHandle.Pinconfig.GPIO_PinOPtyple =GPIO_TYPE_PP;
	GPIOHandle.Pinconfig.GPIO_PinPuPdControl = GPIO_PULL_UP;
	GPIOHandle.Pinconfig.GPIO_Pinspeed = GPIO_SPEED_MEDIUM;

	//Interrupt;
	GPIO_IRQInterruptConfig(IRQ_NUM_EXTI15_10, ENABLE);
	GPIO_IRQInterruptPriority(IRQ_NUM_EXTI15_10, 3);
}
void EXTI15_10_IRQHandler (){
	IRQHandling(GPIO_PIN_11);
	GPIO_ToggleFromInputPin(GPIOA, GPIO_PIN_3);
}
